steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run','test:postman']
    env:
      - 'URL=${_MY_DEPLOYED_URL}'
artifacts:
  objects:
    location: 'gs://lstypkapostman'
    paths: ['newman/*.html']