steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run','test:postman']
artifacts:
  objects:
    location: 'gs://lstypkapostman03122021'
    paths: ['newman/*.html']
